from re import A


x = ("virat koholi")
y = (" is not a GOD")
z = ("but he makes somethinng that is unbeliveble")
print(x, y, z)
print(x.replace("s", "a"))
print(x.replace("a", "r"))
print(y.replace("o", "v"))
print(y.replace("nn", "ok"))
print(z.replace("g", "p"))
print(z.replace("i", "u"))
print(x.upper())
print(x.lower())
print(type(x))

x = "so peoples aare in very ancieted what will happen t the match between india and pakistan"
y = "virat kohli  and hardik pandey is  doing hiis best  for the team so the nation can proud of them "
z = 87, 800, 635, 65, 34, 13
print(x+y)
print(y)
print(z)
print(x.upper())
print(x.lower())
print(x.replace("is", "apl"))
print(x.replace("h", "ok"))
print(x.replace("s", "hn"))
print(x.replace("i", "yh"))
print(x.replace("k", "ai"))
print(x.replace("l", "po"))
print(y.upper())
print(y.lower())
print(y.replace("is", "hl"))
print(y.replace("h", "ok"))
print(y.replace("s", "hn"))
print(y.replace("i", "yh"))
print(y.replace("k", "uj"))
print(y.replace("l", "p"))
print(x.split())
print(y.split())
# boolenans
print(20 > 10)
print(645 < 487)
print(90 > 854)
print(674 < 851)
print(909 < 65)
print(90892 == 896)
print(bool('hello'))
print(bool(999))
